apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: elogistic-core-service-build
  name: elogistic-core-service-build
  namespace: elogistic-core-service
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elogistic-core-service:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker