apiVersion: v1
kind: Service
metadata:
  labels:
    app: marketplace-core-service
  name: marketplace-core-service
  namespace: marketplace-core-service
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: marketplace-core-service
  type: ClusterIP